// Copyright 2012 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by mksyntaxgo from the RE2 distribution. DO NOT EDIT.

/*
Package syntax 将正则表达式解析为解析树，并将解析树编译为程序。
大多数正则表达式的用户将使用 [regexp] 包的功能
（如 [regexp.Compile] 和 [regexp.Match]）而非此包。

# 语法

使用 [Perl] 标志解析时，本包理解的正则表达式语法如下。
可以通过向 [Parse] 传递其他标志来禁用部分语法。

单个字符：

	.              任意字符，可能包括换行符（标志 s=true）
	[xyz]          字符类
	[^xyz]         取反字符类
	\d             Perl 字符类
	\D             取反 Perl 字符类
	[[:alpha:]]    ASCII 字符类
	[[:^alpha:]]   取反 ASCII 字符类
	\pN            Unicode 字符类（单字母名称）
	\p{Greek}      Unicode 字符类
	\PN            取反 Unicode 字符类（单字母名称）
	\P{Greek}      取反 Unicode 字符类

组合：

	xy             x 后接 y
	x|y            x 或 y（优先 x）

重复：

	x*             零个或多个 x，优先更多
	x+             一个或多个 x，优先更多
	x?             零个或一个 x，优先一个
	x{n,m}         n 或 n+1 或 ... 或 m 个 x，优先更多
	x{n,}          n 个或更多 x，优先更多
	x{n}           恰好 n 个 x
	x*?            零个或多个 x，优先更少
	x+?            一个或多个 x，优先更少
	x??            零个或一个 x，优先零个
	x{n,m}?        n 或 n+1 或 ... 或 m 个 x，优先更少
	x{n,}?         n 个或更多 x，优先更少
	x{n}?          恰好 n 个 x

实现限制：计数形式 x{n,m}、x{n,} 和 x{n}
会拒绝最小或最大重复次数超过 1000 的形式。
无限制重复不受此限制。

分组：

	(re)           编号捕获组（子匹配）
	(?P<name>re)   命名且编号的捕获组（子匹配）
	(?<name>re)    命名且编号的捕获组（子匹配）
	(?:re)         非捕获组
	(?flags)       在当前组中设置标志；非捕获
	(?flags:re)    在 re 期间设置标志；非捕获

	标志语法为 xyz（设置）或 -xyz（清除）或 xy-z（设置 xy，清除 z）。标志有：

	i              不区分大小写（默认 false）
	m              多行模式：^ 和 $ 除了匹配文本开头/结尾外还匹配行开头/结尾（默认 false）
	s              让 . 匹配 \n（默认 false）
	U              非贪婪：交换 x* 和 x*?、x+ 和 x+? 等的含义（默认 false）

空字符串：

	^              在文本或行的开头（标志 m=true）
	$              在文本结尾（类似 \z 而非 \Z）或行结尾（标志 m=true）
	\A             在文本开头
	\b             在 ASCII 单词边界（一侧是 \w，另一侧是 \W、\A 或 \z）
	\B             不在 ASCII 单词边界
	\z             在文本结尾

转义序列：

	\a             响铃符（== \007）
	\f             换页符（== \014）
	\t             水平制表符（== \011）
	\n             换行符（== \012）
	\r             回车符（== \015）
	\v             垂直制表符（== \013）
	\*             字面 *，适用于任何标点字符 *
	\123           八进制字符码（最多三位）
	\x7F           十六进制字符码（恰好两位）
	\x{10FFFF}     十六进制字符码
	\Q...\E        字面文本 ... 即使 ... 含有标点

字符类元素：

	x              单个字符
	A-Z            字符范围（含两端）
	\d             Perl 字符类
	[:foo:]        ASCII 字符类 foo
	\p{Foo}        Unicode 字符类 Foo
	\pF            Unicode 字符类 F（单字母名称）

作为字符类元素的命名字符类：

	[\d]           数字（== \d）
	[^\d]          非数字（== \D）
	[\D]           非数字（== \D）
	[^\D]          非非数字（== \d）
	[[:name:]]     字符类内的命名 ASCII 类（== [:name:]）
	[^[:name:]]    取反字符类内的命名 ASCII 类（== [:^name:]）
	[\p{Name}]     字符类内的命名 Unicode 属性（== \p{Name}）
	[^\p{Name}]    取反字符类内的命名 Unicode 属性（== \P{Name}）

Perl 字符类（全部仅限 ASCII）：

	\d             数字（== [0-9]）
	\D             非数字（== [^0-9]）
	\s             空白字符（== [\t\n\f\r ]）
	\S             非空白字符（== [^\t\n\f\r ]）
	\w             单词字符（== [0-9A-Za-z_]）
	\W             非单词字符（== [^0-9A-Za-z_]）

ASCII 字符类：

	[[:alnum:]]    字母数字（== [0-9A-Za-z]）
	[[:alpha:]]    字母（== [A-Za-z]）
	[[:ascii:]]    ASCII（== [\x00-\x7F]）
	[[:blank:]]    空格（== [\t ]）
	[[:cntrl:]]    控制字符（== [\x00-\x1F\x7F]）
	[[:digit:]]    数字（== [0-9]）
	[[:graph:]]    图形字符（== [!-~] == [A-Za-z0-9!"#$%&'()*+,\-./:;<=>?@[\\\]^_`{|}~]）
	[[:lower:]]    小写字母（== [a-z]）
	[[:print:]]    可打印字符（== [ -~] == [ [:graph:]]）
	[[:punct:]]    标点符号（== [!-/:-@[-`{-~]）
	[[:space:]]    空白字符（== [\t\n\v\f\r ]）
	[[:upper:]]    大写字母（== [A-Z]）
	[[:word:]]     单词字符（== [0-9A-Za-z_]）
	[[:xdigit:]]   十六进制数字（== [0-9A-Fa-f]）

Unicode 字符类是 [unicode.Categories]、
[unicode.CategoryAliases] 和 [unicode.Scripts] 中的那些。
*/
package syntax
