// Copyright 2019 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by go generate; DO NOT EDIT.

package suffixarray

func text_64(text []byte, sa []int64) {
	if int(int64(len(text))) != len(text) || len(text) != len(sa) {
		panic("suffixarray: misuse of text_64")
	}
	sais_8_64(text, 256, sa, make([]int64, 2*256))
}

func sais_8_64(text []byte, textMax int, sa, tmp []int64) {
	if len(sa) != len(text) || len(tmp) < textMax {
		panic("suffixarray: misuse of sais_8_64")
	}

	// 简单的基本情况。排序 0 或 1 个元素很容易。
	if len(text) == 0 {
		return
	}
	if len(text) == 1 {
		sa[0] = 0
		return
	}

	// 建立由文本字符索引的切片，
	// 持有字符频率和桶排序偏移量。
	// 如果 tmp 只够一个切片使用，
	// 我们将它作为桶偏移量，并在每次需要时重新计算字符频率。
	var freq, bucket []int64
	if len(tmp) >= 2*textMax {
		freq, bucket = tmp[:textMax], tmp[textMax:2*textMax]
		freq[0] = -1 // 标记为未初始化
	} else {
		freq, bucket = nil, tmp[:textMax]
	}

	// SAIS 算法。
	// 每个调用都通过对 sa 的一次扫描实现。
	// 有关每个函数在算法中的作用，请参见各个函数的文档。
	numLMS := placeLMS_8_64(text, sa, freq, bucket)
	if numLMS <= 1 {
		// 0 或 1 个元素已排序。什么都不做。
	} else {
		induceSubL_8_64(text, sa, freq, bucket)
		induceSubS_8_64(text, sa, freq, bucket)
		length_8_64(text, sa, numLMS)
		maxID := assignID_8_64(text, sa, numLMS)
		if maxID < numLMS {
			map_64(sa, numLMS)
			recurse_64(sa, tmp, numLMS, maxID)
			unmap_8_64(text, sa, numLMS)
		} else {
			// 如果 maxID == numLMS，则每个 LMS 子串都是唯一的，
			// 所以两个 LMS 后缀的相对顺序由前导 LMS 子串决定。
			// 也就是说，LMS 后缀排序顺序与（更简单的）LMS 子串排序顺序匹配。
			// 将原始 LMS 子串顺序复制到后缀数组目标位置。
			copy(sa, sa[len(sa)-numLMS:])
		}
		expand_8_64(text, freq, bucket, sa, numLMS)
	}
	induceL_8_64(text, sa, freq, bucket)
	induceS_8_64(text, sa, freq, bucket)

	// 标记给调用者我们覆盖了 tmp。
	tmp[0] = -1
}

func sais_32(text []int32, textMax int, sa, tmp []int32) {
	if len(sa) != len(text) || len(tmp) < textMax {
		panic("suffixarray: misuse of sais_32")
	}

	// 简单的基本情况。排序 0 或 1 个元素很容易。
	if len(text) == 0 {
		return
	}
	if len(text) == 1 {
		sa[0] = 0
		return
	}

	// 建立由文本字符索引的切片，
	// 持有字符频率和桶排序偏移量。
	// 如果 tmp 只够一个切片使用，
	// 我们将它作为桶偏移量，并在每次需要时重新计算字符频率。
	var freq, bucket []int32
	if len(tmp) >= 2*textMax {
		freq, bucket = tmp[:textMax], tmp[textMax:2*textMax]
		freq[0] = -1 // 标记为未初始化
	} else {
		freq, bucket = nil, tmp[:textMax]
	}

	// SAIS 算法。
	// 每个调用都通过对 sa 的一次扫描实现。
	// 有关每个函数在算法中的作用，请参见各个函数的文档。
	numLMS := placeLMS_32(text, sa, freq, bucket)
	if numLMS <= 1 {
		// 0 或 1 个元素已排序。什么都不做。
	} else {
		induceSubL_32(text, sa, freq, bucket)
		induceSubS_32(text, sa, freq, bucket)
		length_32(text, sa, numLMS)
		maxID := assignID_32(text, sa, numLMS)
		if maxID < numLMS {
			map_32(sa, numLMS)
			recurse_32(sa, tmp, numLMS, maxID)
			unmap_32(text, sa, numLMS)
		} else {
			// 如果 maxID == numLMS，则每个 LMS 子串都是唯一的，
			// 所以两个 LMS 后缀的相对顺序由前导 LMS 子串决定。
			// 也就是说，LMS 后缀排序顺序与（更简单的）LMS 子串排序顺序匹配。
			// 将原始 LMS 子串顺序复制到后缀数组目标位置。
			copy(sa, sa[len(sa)-numLMS:])
		}
		expand_32(text, freq, bucket, sa, numLMS)
	}
	induceL_32(text, sa, freq, bucket)
	induceS_32(text, sa, freq, bucket)

	// 标记给调用者我们覆盖了 tmp。
	tmp[0] = -1
}

func sais_64(text []int64, textMax int, sa, tmp []int64) {
	if len(sa) != len(text) || len(tmp) < textMax {
		panic("suffixarray: misuse of sais_64")
	}

	// 简单的基本情况。排序 0 或 1 个元素很容易。
	if len(text) == 0 {
		return
	}
	if len(text) == 1 {
		sa[0] = 0
		return
	}

	// 建立由文本字符索引的切片，
	// 持有字符频率和桶排序偏移量。
	// 如果 tmp 只够一个切片使用，
	// 我们将它作为桶偏移量，并在每次需要时重新计算字符频率。
	var freq, bucket []int64
	if len(tmp) >= 2*textMax {
		freq, bucket = tmp[:textMax], tmp[textMax:2*textMax]
		freq[0] = -1 // 标记为未初始化
	} else {
		freq, bucket = nil, tmp[:textMax]
	}

	// SAIS 算法。
	// 每个调用都通过对 sa 的一次扫描实现。
	// 有关每个函数在算法中的作用，请参见各个函数的文档。
	numLMS := placeLMS_64(text, sa, freq, bucket)
	if numLMS <= 1 {
		// 0 或 1 个元素已排序。什么都不做。
	} else {
		induceSubL_64(text, sa, freq, bucket)
		induceSubS_64(text, sa, freq, bucket)
		length_64(text, sa, numLMS)
		maxID := assignID_64(text, sa, numLMS)
		if maxID < numLMS {
			map_64(sa, numLMS)
			recurse_64(sa, tmp, numLMS, maxID)
			unmap_64(text, sa, numLMS)
		} else {
			// 如果 maxID == numLMS，则每个 LMS 子串都是唯一的，
			// 所以两个 LMS 后缀的相对顺序由前导 LMS 子串决定。
			// 也就是说，LMS 后缀排序顺序与（更简单的）LMS 子串排序顺序匹配。
			// 将原始 LMS 子串顺序复制到后缀数组目标位置。
			copy(sa, sa[len(sa)-numLMS:])
		}
		expand_64(text, freq, bucket, sa, numLMS)
	}
	induceL_64(text, sa, freq, bucket)
	induceS_64(text, sa, freq, bucket)

	// 标记给调用者我们覆盖了 tmp。
	tmp[0] = -1
}

func freq_8_64(text []byte, freq, bucket []int64) []int64 {
	if freq != nil && freq[0] >= 0 {
		return freq // 已计算
	}
	if freq == nil {
		freq = bucket
	}

	freq = freq[:256] // 消除下面 freq[c] 的边界检查
	clear(freq)
	for _, c := range text {
		freq[c]++
	}
	return freq
}

func freq_32(text []int32, freq, bucket []int32) []int32 {
	if freq != nil && freq[0] >= 0 {
		return freq // 已计算
	}
	if freq == nil {
		freq = bucket
	}

	clear(freq)
	for _, c := range text {
		freq[c]++
	}
	return freq
}

func freq_64(text []int64, freq, bucket []int64) []int64 {
	if freq != nil && freq[0] >= 0 {
		return freq // 已计算
	}
	if freq == nil {
		freq = bucket
	}

	clear(freq)
	for _, c := range text {
		freq[c]++
	}
	return freq
}

func bucketMin_8_64(text []byte, freq, bucket []int64) {
	freq = freq_8_64(text, freq, bucket)
	freq = freq[:256]     // 确定 len(freq) = 256，所以下面 0 ≤ i < 256
	bucket = bucket[:256] // 消除下面 bucket[i] 的边界检查
	total := int64(0)
	for i, n := range freq {
		bucket[i] = total
		total += n
	}
}

func bucketMin_32(text []int32, freq, bucket []int32) {
	freq = freq_32(text, freq, bucket)
	total := int32(0)
	for i, n := range freq {
		bucket[i] = total
		total += n
	}
}

func bucketMin_64(text []int64, freq, bucket []int64) {
	freq = freq_64(text, freq, bucket)
	total := int64(0)
	for i, n := range freq {
		bucket[i] = total
		total += n
	}
}

func bucketMax_8_64(text []byte, freq, bucket []int64) {
	freq = freq_8_64(text, freq, bucket)
	freq = freq[:256]     // 确定 len(freq) = 256，所以下面 0 ≤ i < 256
	bucket = bucket[:256] // 消除下面 bucket[i] 的边界检查
	total := int64(0)
	for i, n := range freq {
		total += n
		bucket[i] = total
	}
}

func bucketMax_32(text []int32, freq, bucket []int32) {
	freq = freq_32(text, freq, bucket)
	total := int32(0)
	for i, n := range freq {
		total += n
		bucket[i] = total
	}
}

func bucketMax_64(text []int64, freq, bucket []int64) {
	freq = freq_64(text, freq, bucket)
	total := int64(0)
	for i, n := range freq {
		total += n
		bucket[i] = total
	}
}

func placeLMS_8_64(text []byte, sa, freq, bucket []int64) int {
	bucketMax_8_64(text, freq, bucket)

	numLMS := 0
	lastB := int64(-1)
	bucket = bucket[:256] // 消除下面 bucket[c1] 的边界检查

	// 接下来的这段代码（直到空行）向后遍历 text，
	// 在每个满足 text[i] 是 L 型字符而 text[i+1] 是 S 型字符的位置 i 处
	// 执行代码体。
	// 也就是说，i+1 是 LMS 子串的起始位置。
	// 这些代码可以提取到一个带有回调函数的函数中，
	// 但会以显著的速度为代价。相反，我们只是在这个源文件中
	// 多次编写这七行代码。下面的副本参考了
	// 这个原始模式，称之为"LMS 子串迭代器"。
	//
	// 在每次遍历 text 的扫描中，c0、c1 是 text 中连续的字符。
	// 在这个后向扫描中，c0 == text[i] 而 c1 == text[i+1]。
	// 通过后向扫描，我们可以根据以下通常的定义
	// 跟踪当前位置是 S 型还是 L 型：
	//
	//	- 位置 len(text) 是 S 型，text[len(text)] == -1（哨兵）
	//	- 如果 text[i] < text[i+1]，或者 text[i] == text[i+1] 且 i+1 是 S 型，则位置 i 是 S 型。
	//	- 如果 text[i] > text[i+1]，或者 text[i] == text[i+1] 且 i+1 是 L 型，则位置 i 是 L 型。
	//
	// 后向扫描让我们能够保持当前的类型，
	// 当看到 c0 != c1 时更新它，否则保持不变。
	// 我们想要识别所有前面有 L 的 S 位置。
	// 根据定义，位置 len(text) 就是这样的位置，但是我们
	// 没有地方来记录它，所以通过在循环开始时不真实地
	// 设置 isTypeS = false 来消除它。
	c0, c1, isTypeS := byte(0), byte(0), false
	for i := len(text) - 1; i >= 0; i-- {
		c0, c1 = text[i], c0
		if c0 < c1 {
			isTypeS = true
		} else if c0 > c1 && isTypeS {
			isTypeS = false

			// 将索引 i+1 桶排序为 LMS 子串的起始。
			b := bucket[c1] - 1
			bucket[c1] = b
			sa[b] = int64(i + 1)
			lastB = b
			numLMS++
		}
	}

	// 我们记录了 LMS 子串的起始索引，但实际上想要的是结束索引。
	// 幸运的是，有两个区别，起始索引和结束索引是相同的。
	// 第一个区别是最右边 LMS 子串的结束索引是 len(text)，
	// 所以调用者必须假设 sa[-1] == len(text)，如上所述。
	// 第二个区别是最左边 LMS 子串的起始索引
	// 不是前一个 LMS 子串的结束索引，
	// 所以作为优化，我们可以省略最左边的 LMS 子串起始索引（我们写入的最后一个）。
	//
	// 例外：如果 numLMS <= 1，调用者根本不会进行递归，
	// 会将结果视为包含 LMS 子串的起始索引。
	// 在这种情况下，我们不会删除最后一个条目。
	if numLMS > 1 {
		sa[lastB] = 0
	}
	return numLMS
}

func placeLMS_32(text []int32, sa, freq, bucket []int32) int {
	bucketMax_32(text, freq, bucket)

	numLMS := 0
	lastB := int32(-1)

	// 接下来的这段代码（直到空行）向后遍历 text，
	// 在每个满足 text[i] 是 L 型字符而 text[i+1] 是 S 型字符的位置 i 处
	// 执行代码体。
	// 也就是说，i+1 是 LMS 子串的起始位置。
	// 这些代码可以提取到一个带有回调函数的函数中，
	// 但会以显著的速度为代价。相反，我们只是在这个源文件中
	// 多次编写这七行代码。下面的副本参考了
	// 这个原始模式，称之为"LMS 子串迭代器"。
	//
	// 在每次遍历 text 的扫描中，c0、c1 是 text 中连续的字符。
	// 在这个后向扫描中，c0 == text[i] 而 c1 == text[i+1]。
	// 通过后向扫描，我们可以根据以下通常的定义
	// 跟踪当前位置是 S 型还是 L 型：
	//
	//	- 位置 len(text) 是 S 型，text[len(text)] == -1（哨兵）
	//	- 如果 text[i] < text[i+1]，或者 text[i] == text[i+1] 且 i+1 是 S 型，则位置 i 是 S 型。
	//	- 如果 text[i] > text[i+1]，或者 text[i] == text[i+1] 且 i+1 是 L 型，则位置 i 是 L 型。
	//
	// 后向扫描让我们能够保持当前的类型，
	// 当看到 c0 != c1 时更新它，否则保持不变。
	// 我们想要识别所有前面有 L 的 S 位置。
	// 根据定义，位置 len(text) 就是这样的位置，但是我们
	// 没有地方来记录它，所以通过在循环开始时不真实地
	// 设置 isTypeS = false 来消除它。
	c0, c1, isTypeS := int32(0), int32(0), false
	for i := len(text) - 1; i >= 0; i-- {
		c0, c1 = text[i], c0
		if c0 < c1 {
			isTypeS = true
		} else if c0 > c1 && isTypeS {
			isTypeS = false

			// 将索引 i+1 桶排序为 LMS 子串的起始。
			b := bucket[c1] - 1
			bucket[c1] = b
			sa[b] = int32(i + 1)
			lastB = b
			numLMS++
		}
	}

	// 我们记录了 LMS 子串的起始索引，但实际上想要的是结束索引。
	// 幸运的是，有两个区别，起始索引和结束索引是相同的。
	// 第一个区别是最右边 LMS 子串的结束索引是 len(text)，
	// 所以调用者必须假设 sa[-1] == len(text)，如上所述。
	// 第二个区别是最左边 LMS 子串的起始索引
	// 不是前一个 LMS 子串的结束索引，
	// 所以作为优化，我们可以省略最左边的 LMS 子串起始索引（我们写入的最后一个）。
	//
	// 例外：如果 numLMS <= 1，调用者根本不会进行递归，
	// 会将结果视为包含 LMS 子串的起始索引。
	// 在这种情况下，我们不会删除最后一个条目。
	if numLMS > 1 {
		sa[lastB] = 0
	}
	return numLMS
}

func placeLMS_64(text []int64, sa, freq, bucket []int64) int {
	bucketMax_64(text, freq, bucket)

	numLMS := 0
	lastB := int64(-1)

	// 接下来的这段代码（直到空行）向后遍历 text，
	// 在每个满足 text[i] 是 L 型字符而 text[i+1] 是 S 型字符的位置 i 处
	// 执行代码体。
	// 也就是说，i+1 是 LMS 子串的起始位置。
	// 这些代码可以提取到一个带有回调函数的函数中，
	// 但会以显著的速度为代价。相反，我们只是在这个源文件中
	// 多次编写这七行代码。下面的副本参考了
	// 这个原始模式，称之为"LMS 子串迭代器"。
	//
	// 在每次遍历 text 的扫描中，c0、c1 是 text 中连续的字符。
	// 在这个后向扫描中，c0 == text[i] 而 c1 == text[i+1]。
	// 通过后向扫描，我们可以根据以下通常的定义
	// 跟踪当前位置是 S 型还是 L 型：
	//
	//	- 位置 len(text) 是 S 型，text[len(text)] == -1（哨兵）
	//	- 如果 text[i] < text[i+1]，或者 text[i] == text[i+1] 且 i+1 是 S 型，则位置 i 是 S 型。
	//	- 如果 text[i] > text[i+1]，或者 text[i] == text[i+1] 且 i+1 是 L 型，则位置 i 是 L 型。
	//
	// 后向扫描让我们能够保持当前的类型，
	// 当看到 c0 != c1 时更新它，否则保持不变。
	// 我们想要识别所有前面有 L 的 S 位置。
	// 根据定义，位置 len(text) 就是这样的位置，但是我们
	// 没有地方来记录它，所以通过在循环开始时不真实地
	// 设置 isTypeS = false 来消除它。
	c0, c1, isTypeS := int64(0), int64(0), false
	for i := len(text) - 1; i >= 0; i-- {
		c0, c1 = text[i], c0
		if c0 < c1 {
			isTypeS = true
		} else if c0 > c1 && isTypeS {
			isTypeS = false

			// 将索引 i+1 桶排序为 LMS 子串的起始。
			b := bucket[c1] - 1
			bucket[c1] = b
			sa[b] = int64(i + 1)
			lastB = b
			numLMS++
		}
	}

	// 我们记录了 LMS 子串的起始索引，但实际上想要的是结束索引。
	// 幸运的是，有两个区别，起始索引和结束索引是相同的。
	// 第一个区别是最右边 LMS 子串的结束索引是 len(text)，
	// 所以调用者必须假设 sa[-1] == len(text)，如上所述。
	// 第二个区别是最左边 LMS 子串的起始索引
	// 不是前一个 LMS 子串的结束索引，
	// 所以作为优化，我们可以省略最左边的 LMS 子串起始索引（我们写入的最后一个）。
	//
	// 例外：如果 numLMS <= 1，调用者根本不会进行递归，
	// 会将结果视为包含 LMS 子串的起始索引。
	// 在这种情况下，我们不会删除最后一个条目。
	if numLMS > 1 {
		sa[lastB] = 0
	}
	return numLMS
}

func induceSubL_8_64(text []byte, sa, freq, bucket []int64) {
	// 初始化字符桶左侧的位置。
	bucketMin_8_64(text, freq, bucket)
	bucket = bucket[:256] // 消除下面 bucket[cB] 的边界检查

	// 当我们从左到右扫描数组时，每个 sa[i] = j > 0 是一个正确的
	// 排序后缀数组条目（对于 text[j:]），我们知道 j-1 是 L 型。
	// 因为 j-1 是 L 型，现在将它插入 sa 会正确排序。
	// 但我们想要区分 j-1 前面是 L 型还是 S 型的情况。
	// 如果 j-1 前面是 S 型，我们可以通过取反 j-1 来记录区别，
	// 这样调用者就能跳过它。
	// 无论哪种情况，插入（到 text[j-1] 桶中）保证会
	// 发生在 sa[i´] 处，其中 i´ > i，也就是说，在尚未扫描的 sa 部分中。
	// 因此单次扫描会按排序但不一定相邻的顺序看到索引 j、j-1、j-2、j-3，
	// 等等，直到找到一个前面是 S 型索引的索引，此时它必须停止。
	//
	// 当我们遍历数组时，我们清除已处理的条目（sa[i] > 0）为零，
	// 并将 sa[i] < 0 翻转为 -sa[i]，
	// 以便循环结束时 sa 只包含每个 LMS 子串最左边的 L 型索引。
	//
	// 因此，后缀数组 sa 同时充当输入、输出
	// 以及一个精心设计的工作队列。

	// placeLMS_8_64 遗漏了隐含的条目 sa[-1] == len(text)，
	// 对应于识别的 L 型索引 len(text)-1。
	// 在从左到右正式扫描 sa 之前处理它。
	// 参见循环中的正文注释。
	k := len(text) - 1
	c0, c1 := text[k-1], text[k]
	if c0 < c1 {
		k = -k
	}

	// 缓存最近使用的桶索引：
	// 我们按排序顺序处理后缀，
	// 访问由排序顺序前的字节索引的桶，
	// 这仍然具有非常好的局部性。
	// 不变式：b 是 bucket[cB] 的缓存，可能是脏拷贝。
	cB := c1
	b := bucket[cB]
	sa[b] = int64(k)
	b++

	for i := 0; i < len(sa); i++ {
		j := int(sa[i])
		if j == 0 {
			// 跳过空条目。
			continue
		}
		if j < 0 {
			// 保留发现 S 型索引给调用者。
			sa[i] = int64(-j)
			continue
		}
		sa[i] = 0

		// 索引 j 在工作队列中，意味着 k := j-1 是 L 型，
		// 所以我们现在可以将 k 正确地放入 sa。
		// 如果 k-1 是 L 型，将 k 排队以便稍后在此循环中处理。
		// 如果 k-1 是 S 型（text[k-1] < text[k]），将 -k 排队保留给调用者。
		k := j - 1
		c0, c1 := text[k-1], text[k]
		if c0 < c1 {
			k = -k
		}

		if cB != c1 {
			bucket[cB] = b
			cB = c1
			b = bucket[cB]
		}
		sa[b] = int64(k)
		b++
	}
}

func induceSubL_32(text []int32, sa, freq, bucket []int32) {
	// 初始化字符桶左侧的位置。
	bucketMin_32(text, freq, bucket)

	// 当我们从左到右扫描数组时，每个 sa[i] = j > 0 是一个正确的
	// 排序后缀数组条目（对于 text[j:]），我们知道 j-1 是 L 型。
	// 因为 j-1 是 L 型，现在将它插入 sa 会正确排序。
	// 但我们想要区分 j-1 前面是 L 型还是 S 型的情况。
	// 如果 j-1 前面是 S 型，我们可以通过取反 j-1 来记录区别，
	// 这样调用者就能跳过它。
	// 无论哪种情况，插入（到 text[j-1] 桶中）保证会
	// 发生在 sa[i´] 处，其中 i´ > i，也就是说，在尚未扫描的 sa 部分中。
	// 因此单次扫描会按排序但不一定相邻的顺序看到索引 j、j-1、j-2、j-3，
	// 等等，直到找到一个前面是 S 型索引的索引，此时它必须停止。
	//
	// 当我们遍历数组时，我们清除已处理的条目（sa[i] > 0）为零，
	// 并将 sa[i] < 0 翻转为 -sa[i]，
	// 以便循环结束时 sa 只包含每个 LMS 子串最左边的 L 型索引。
	//
	// 因此，后缀数组 sa 同时充当输入、输出
	// 以及一个精心设计的工作队列。

	// placeLMS_32 遗漏了隐含的条目 sa[-1] == len(text)，
	// 对应于识别的 L 型索引 len(text)-1。
	// 在从左到右正式扫描 sa 之前处理它。
	// 参见循环中的正文注释。
	k := len(text) - 1
	c0, c1 := text[k-1], text[k]
	if c0 < c1 {
		k = -k
	}

	// 缓存最近使用的桶索引：
	// 我们按排序顺序处理后缀，
	// 访问由排序顺序前的 int32 索引的桶，
	// 这仍然具有非常好的局部性。
	// 不变式：b 是 bucket[cB] 的缓存，可能是脏拷贝。
	cB := c1
	b := bucket[cB]
	sa[b] = int32(k)
	b++

	for i := 0; i < len(sa); i++ {
		j := int(sa[i])
		if j == 0 {
			// 跳过空条目。
			continue
		}
		if j < 0 {
			// 保留发现 S 型索引给调用者。
			sa[i] = int32(-j)
			continue
		}
		sa[i] = 0

		// 索引 j 在工作队列中，意味着 k := j-1 是 L 型，
		// 所以我们现在可以将 k 正确地放入 sa。
		// 如果 k-1 是 L 型，将 k 排队以便稍后在此循环中处理。
		// 如果 k-1 是 S 型（text[k-1] < text[k]），将 -k 排队保留给调用者。
		k := j - 1
		c0, c1 := text[k-1], text[k]
		if c0 < c1 {
			k = -k
		}

		if cB != c1 {
			bucket[cB] = b
			cB = c1
			b = bucket[cB]
		}
		sa[b] = int32(k)
		b++
	}
}

func induceSubL_64(text []int64, sa, freq, bucket []int64) {
	// 初始化字符桶左侧的位置。
	bucketMin_64(text, freq, bucket)

	// 当我们从左到右扫描数组时，每个 sa[i] = j > 0 是一个正确的
	// 排序后缀数组条目（对于 text[j:]），我们知道 j-1 是 L 型。
	// 因为 j-1 是 L 型，现在将它插入 sa 会正确排序。
	// 但我们想要区分 j-1 前面是 L 型还是 S 型的情况。
	// 如果 j-1 前面是 S 型，我们可以通过取反 j-1 来记录区别，
	// 这样调用者就能跳过它。
	// 无论哪种情况，插入（到 text[j-1] 桶中）保证会
	// 发生在 sa[i´] 处，其中 i´ > i，也就是说，在尚未扫描的 sa 部分中。
	// 因此单次扫描会按排序但不一定相邻的顺序看到索引 j、j-1、j-2、j-3，
	// 等等，直到找到一个前面是 S 型索引的索引，此时它必须停止。
	//
	// 当我们遍历数组时，我们清除已处理的条目（sa[i] > 0）为零，
	// 并将 sa[i] < 0 翻转为 -sa[i]，
	// 以便循环结束时 sa 只包含每个 LMS 子串最左边的 L 型索引。
	//
	// 因此，后缀数组 sa 同时充当输入、输出
	// 以及一个精心设计的工作队列。

	// placeLMS_64 遗漏了隐含的条目 sa[-1] == len(text)，
	// 对应于识别的 L 型索引 len(text)-1。
	// 在从左到右正式扫描 sa 之前处理它。
	// 参见循环中的正文注释。
	k := len(text) - 1
	c0, c1 := text[k-1], text[k]
	if c0 < c1 {
		k = -k
	}

	// 缓存最近使用的桶索引：
	// 我们按排序顺序处理后缀，
	// 访问由排序顺序前的 int64 索引的桶，
	// 这仍然具有非常好的局部性。
	// 不变式：b 是 bucket[cB] 的缓存，可能是脏拷贝。
	cB := c1
	b := bucket[cB]
	sa[b] = int64(k)
	b++

	for i := 0; i < len(sa); i++ {
		j := int(sa[i])
		if j == 0 {
			// 跳过空条目。
			continue
		}
		if j < 0 {
			// 保留发现 S 型索引给调用者。
			sa[i] = int64(-j)
			continue
		}
		sa[i] = 0

		// 索引 j 在工作队列中，意味着 k := j-1 是 L 型，
		// 所以我们现在可以将 k 正确地放入 sa。
		// 如果 k-1 是 L 型，将 k 排队以便稍后在此循环中处理。
		// 如果 k-1 是 S 型（text[k-1] < text[k]），将 -k 排队保留给调用者。
		k := j - 1
		c0, c1 := text[k-1], text[k]
		if c0 < c1 {
			k = -k
		}

		if cB != c1 {
			bucket[cB] = b
			cB = c1
			b = bucket[cB]
		}
		sa[b] = int64(k)
		b++
	}
}

func induceSubS_8_64(text []byte, sa, freq, bucket []int64) {
	// 初始化字符桶右侧的位置。
	bucketMax_8_64(text, freq, bucket)
	bucket = bucket[:256] // 消除下面 bucket[cB] 的边界检查

	// 类似于上面的 induceSubL_8_64，
	// 当我们从右到左扫描数组时，每个 sa[i] = j > 0 是一个正确的
	// 排序后缀数组条目（对于 text[j:]），我们知道 j-1 是 S 型。
	// 因为 j-1 是 S 型，现在将它插入 sa 会正确排序。
	// 但我们想要区分 j-1 前面是 S 型还是 L 型的情况。
	// 如果 j-1 前面是 L 型，我们可以通过取反 j-1 来记录区别，
	// 这样调用者就能跳过它。
	// 无论哪种情况，插入（到 text[j-1] 桶中）保证会
	// 发生在 sa[i´] 处，其中 i´ < i，也就是说，在尚未扫描的 sa 部分中。
	// 因此单次扫描会按排序但不一定相邻的顺序看到索引 j、j-1、j-2、j-3，
	// 等等，直到找到一个前面是 L 型索引的索引，此时它必须停止。
	// 那个索引（前面是 L 型）是一个 LMS 子串的起始。
	//
	// 当我们遍历数组时，我们清除已处理的条目（sa[i] > 0）为零，
	// 并将 sa[i] < 0 翻转为 -sa[i] 并压缩到 sa 的顶部，
	// 以便循环结束时 sa 的顶部正好包含
	// LMS 子串起始索引，按 LMS 子串排序。

	// 缓存最近使用的桶索引。
	cB := byte(0)
	b := bucket[cB]

	top := len(sa)
	for i := len(sa) - 1; i >= 0; i-- {
		j := int(sa[i])
		if j == 0 {
			// 跳过空条目。
			continue
		}
		sa[i] = 0
		if j < 0 {
			// 保留发现的 LMS 子串起始索引给调用者。
			top--
			sa[top] = int64(-j)
			continue
		}

		// 索引 j 在工作队列中，意味着 k := j-1 是 S 型，
		// 所以我们现在可以将 k 正确地放入 sa。
		// 如果 k-1 是 S 型，将 k 排队以便稍后在此循环中处理。
		// 如果 k-1 是 L 型（text[k-1] > text[k]），将 -k 排队保留给调用者。
		k := j - 1
		c1 := text[k]
		c0 := text[k-1]
		if c0 > c1 {
			k = -k
		}

		if cB != c1 {
			bucket[cB] = b
			cB = c1
			b = bucket[cB]
		}
		b--
		sa[b] = int64(k)
	}
}

func induceSubS_32(text []int32, sa, freq, bucket []int32) {
	// 初始化字符桶右侧的位置。
	bucketMax_32(text, freq, bucket)

	// 类似于上面的 induceSubL_32，
	// 当我们从右到左扫描数组时，每个 sa[i] = j > 0 是一个正确的
	// 排序后缀数组条目（对于 text[j:]），我们知道 j-1 是 S 型。
	// 因为 j-1 是 S 型，现在将它插入 sa 会正确排序。
	// 但我们想要区分 j-1 前面是 S 型还是 L 型的情况。
	// 如果 j-1 前面是 L 型，我们可以通过取反 j-1 来记录区别，
	// 这样调用者就能跳过它。
	// 无论哪种情况，插入（到 text[j-1] 桶中）保证会
	// 发生在 sa[i´] 处，其中 i´ < i，也就是说，在尚未扫描的 sa 部分中。
	// 因此单次扫描会按排序但不一定相邻的顺序看到索引 j、j-1、j-2、j-3，
	// 等等，直到找到一个前面是 L 型索引的索引，此时它必须停止。
	// 那个索引（前面是 L 型）是一个 LMS 子串的起始。
	//
	// 当我们遍历数组时，我们清除已处理的条目（sa[i] > 0）为零，
	// 并将 sa[i] < 0 翻转为 -sa[i] 并压缩到 sa 的顶部，
	// 以便循环结束时 sa 的顶部正好包含
	// LMS 子串起始索引，按 LMS 子串排序。

	// 缓存最近使用的桶索引。
	cB := int32(0)
	b := bucket[cB]

	top := len(sa)
	for i := len(sa) - 1; i >= 0; i-- {
		j := int(sa[i])
		if j == 0 {
			// 跳过空条目。
			continue
		}
		sa[i] = 0
		if j < 0 {
			// 保留发现的 LMS 子串起始索引给调用者。
			top--
			sa[top] = int32(-j)
			continue
		}

		// 索引 j 在工作队列中，意味着 k := j-1 是 S 型，
		// 所以我们现在可以将 k 正确地放入 sa。
		// 如果 k-1 是 S 型，将 k 排队以便稍后在此循环中处理。
		// 如果 k-1 是 L 型（text[k-1] > text[k]），将 -k 排队保留给调用者。
		k := j - 1
		c1 := text[k]
		c0 := text[k-1]
		if c0 > c1 {
			k = -k
		}

		if cB != c1 {
			bucket[cB] = b
			cB = c1
			b = bucket[cB]
		}
		b--
		sa[b] = int32(k)
	}
}

func induceSubS_64(text []int64, sa, freq, bucket []int64) {
	// 初始化字符桶右侧的位置。
	bucketMax_64(text, freq, bucket)

	// 类似于上面的 induceSubL_64，
	// 当我们从右到左扫描数组时，每个 sa[i] = j > 0 是一个正确的
	// 排序后缀数组条目（对于 text[j:]），我们知道 j-1 是 S 型。
	// 因为 j-1 是 S 型，现在将它插入 sa 会正确排序。
	// 但我们想要区分 j-1 前面是 S 型还是 L 型的情况。
	// 如果 j-1 前面是 L 型，我们可以通过取反 j-1 来记录区别，
	// 这样调用者就能跳过它。
	// 无论哪种情况，插入（到 text[j-1] 桶中）保证会
	// 发生在 sa[i´] 处，其中 i´ < i，也就是说，在尚未扫描的 sa 部分中。
	// 因此单次扫描会按排序但不一定相邻的顺序看到索引 j、j-1、j-2、j-3，
	// 等等，直到找到一个前面是 L 型索引的索引，此时它必须停止。
	// 那个索引（前面是 L 型）是一个 LMS 子串的起始。
	//
	// 当我们遍历数组时，我们清除已处理的条目（sa[i] > 0）为零，
	// 并将 sa[i] < 0 翻转为 -sa[i] 并压缩到 sa 的顶部，
	// 以便循环结束时 sa 的顶部正好包含
	// LMS 子串起始索引，按 LMS 子串排序。

	// 缓存最近使用的桶索引。
	cB := int64(0)
	b := bucket[cB]

	top := len(sa)
	for i := len(sa) - 1; i >= 0; i-- {
		j := int(sa[i])
		if j == 0 {
			// 跳过空条目。
			continue
		}
		sa[i] = 0
		if j < 0 {
			// 保留发现的 LMS 子串起始索引给调用者。
			top--
			sa[top] = int64(-j)
			continue
		}

		// 索引 j 在工作队列中，意味着 k := j-1 是 S 型，
		// 所以我们现在可以将 k 正确地放入 sa。
		// 如果 k-1 是 S 型，将 k 排队以便稍后在此循环中处理。
		// 如果 k-1 是 L 型（text[k-1] > text[k]），将 -k 排队保留给调用者。
		k := j - 1
		c1 := text[k]
		c0 := text[k-1]
		if c0 > c1 {
			k = -k
		}

		if cB != c1 {
			bucket[cB] = b
			cB = c1
			b = bucket[cB]
		}
		b--
		sa[b] = int64(k)
	}
}

func length_8_64(text []byte, sa []int64, numLMS int) {
	end := 0 // 当前 LMS 子串结尾的索引（0 表示最后一个 LMS 子串）

	// 将 N 个文本字节编码为一个"长度"字，
	// 对每个字节加 1，将它们打包到字的底部
	// N*8 位中，然后按位取反结果。
	// 也就是说，文本序列 A B C（十六进制 41 42 43）
	// 编码为 ^uint64(0x42_43_44)。
	// LMS 子串永远不能以 0xFF 开头或结尾。
	// 加 1 确保编码后的字节序列永远不以 0x00 开头或结尾，
	// 这样存在的字节就可以与高位的零填充区分开来，
	// 因此长度不需要单独编码。
	// 取反字节增加了 4 字节编码仍然 ≥ len(text) 的机会。
	// 特别是，如果第一个字节是 ASCII（<= 0x7E，所以 +1 <= 0x7F），
	// 那么取反的高位将被设置，
	// 使其明显不是有效的长度（它将是负数）。
	//
	// cx 持有取反前的编码（打包的递增字节）。
	cx := uint64(0) // byte-only

	// 这一节（直到空行）是"LMS 子串迭代器"，
	// 在上面 placeLMS_8_64 中描述的，
	// 添加了一行来维护 cx。
	c0, c1, isTypeS := byte(0), byte(0), false
	for i := len(text) - 1; i >= 0; i-- {
		c0, c1 = text[i], c0
		cx = cx<<8 | uint64(c1+1) // byte-only
		if c0 < c1 {
			isTypeS = true
		} else if c0 > c1 && isTypeS {
			isTypeS = false

			// 索引 j = i+1 是 LMS 子串的开始。
			// 计算长度或编码文本存储到 sa[j/2] 中。
			j := i + 1
			var code int64
			if end == 0 {
				code = 0
			} else {
				code = int64(end - j)
				if code <= 64/8 && ^cx >= uint64(len(text)) { // byte-only
					code = int64(^cx) // byte-only
				} // byte-only
}
			sa[j>>1] = code
			end = j + 1
			cx = uint64(c1 + 1) // byte-only
		}
	}
}

func length_32(text []int32, sa []int32, numLMS int) {
	end := 0 // 当前 LMS 子串结尾的索引（0 表示最后一个 LMS 子串）

	// 将 N 个文本 int32 编码为一个"长度"字，
	// 对每个 int32 加 1，将它们打包到字的底部
	// N*8 位中，然后按位取反结果。
	// 也就是说，文本序列 A B C（十六进制 41 42 43）
	// 编码为 ^uint32(0x42_43_44)。
	// LMS 子串永远不能以 0xFF 开头或结尾。
	// 加 1 确保编码后的 int32 序列永远不以 0x00 开头或结尾，
	// 这样存在的 int32 就可以与高位的零填充区分开来，
	// 因此长度不需要单独编码。
	// 取反 int32 增加了 4-int32 编码仍然 ≥ len(text) 的机会。
	// 特别是，如果第一个 int32 是 ASCII（<= 0x7E，所以 +1 <= 0x7F），
	// 那么取反的高位将被设置，
	// 使其明显不是有效的长度（它将是负数）。
	//
	// cx 持有取反前的编码（打包的递增 int32）。

	// 这一节（直到空行）是"LMS 子串迭代器"，
	// 在上面 placeLMS_32 中描述的，
	// 添加了一行来维护 cx。
	c0, c1, isTypeS := int32(0), int32(0), false
	for i := len(text) - 1; i >= 0; i-- {
		c0, c1 = text[i], c0
		if c0 < c1 {
			isTypeS = true
		} else if c0 > c1 && isTypeS {
			isTypeS = false

			// 索引 j = i+1 是 LMS 子串的开始。
			// 计算长度或编码文本存储到 sa[j/2] 中。
			j := i + 1
			var code int32
			if end == 0 {
				code = 0
			} else {
				code = int32(end - j)
}
			sa[j>>1] = code
			end = j + 1
		}
	}
}

func length_64(text []int64, sa []int64, numLMS int) {
	end := 0 // 当前 LMS 子串结尾的索引（0 表示最后一个 LMS 子串）

	// 将 N 个文本 int64 编码为一个"长度"字，
	// 对每个 int64 加 1，将它们打包到字的底部
	// N*8 位中，然后按位取反结果。
	// 也就是说，文本序列 A B C（十六进制 41 42 43）
	// 编码为 ^uint64(0x42_43_44)。
	// LMS 子串永远不能以 0xFF 开头或结尾。
	// 加 1 确保编码后的 int64 序列永远不以 0x00 开头或结尾，
	// 这样存在的 int64 就可以与高位的零填充区分开来，
	// 因此长度不需要单独编码。
	// 取反 int64 增加了 4-int64 编码仍然 ≥ len(text) 的机会。
	// 特别是，如果第一个 int64 是 ASCII（<= 0x7E，所以 +1 <= 0x7F），
	// 那么取反的高位将被设置，
	// 使其明显不是有效的长度（它将是负数）。
	//
	// cx 持有取反前的编码（打包的递增 int64）。

	// 这一节（直到空行）是"LMS 子串迭代器"，
	// 在上面 placeLMS_64 中描述的，
	// 添加了一行来维护 cx。
	c0, c1, isTypeS := int64(0), int64(0), false
	for i := len(text) - 1; i >= 0; i-- {
		c0, c1 = text[i], c0
		if c0 < c1 {
			isTypeS = true
		} else if c0 > c1 && isTypeS {
			isTypeS = false

			// 索引 j = i+1 是 LMS 子串的开始。
			// 计算长度或编码文本存储到 sa[j/2] 中。
			j := i + 1
			var code int64
			if end == 0 {
				code = 0
			} else {
				code = int64(end - j)
}
			sa[j>>1] = code
			end = j + 1
		}
	}
}

func assignID_8_64(text []byte, sa []int64, numLMS int) int {
	id := 0
	lastLen := int64(-1) // 不可能值
	lastPos := int64(0)
	for _, j := range sa[len(sa)-numLMS:] {
		// 索引 j 处的 LMS 子串是新的，还是与我们看到的最后一个相同？
		n := sa[j/2]
		if n != lastLen {
			goto New
		}
		if uint64(n) >= uint64(len(text)) {
			// “Length” is really encoded full text, and they match.
			goto Same
		}
		{
			// Compare actual texts.
			n := int(n)
			this := text[j:][:n]
			last := text[lastPos:][:n]
			for i := 0; i < n; i++ {
				if this[i] != last[i] {
					goto New
				}
			}
			goto Same
		}
	New:
		id++
		lastPos = j
		lastLen = n
	Same:
		sa[j/2] = int64(id)
	}
	return id
}

func assignID_32(text []int32, sa []int32, numLMS int) int {
	id := 0
	lastLen := int32(-1) // impossible
	lastPos := int32(0)
	for _, j := range sa[len(sa)-numLMS:] {
		// Is the LMS-substring at index j new, or is it the same as the last one we saw?
		n := sa[j/2]
		if n != lastLen {
			goto New
		}
		if uint32(n) >= uint32(len(text)) {
			// “Length” is really encoded full text, and they match.
			goto Same
		}
		{
			// Compare actual texts.
			n := int(n)
			this := text[j:][:n]
			last := text[lastPos:][:n]
			for i := 0; i < n; i++ {
				if this[i] != last[i] {
					goto New
				}
			}
			goto Same
		}
	New:
		id++
		lastPos = j
		lastLen = n
	Same:
		sa[j/2] = int32(id)
	}
	return id
}

func assignID_64(text []int64, sa []int64, numLMS int) int {
	id := 0
	lastLen := int64(-1) // impossible
	lastPos := int64(0)
	for _, j := range sa[len(sa)-numLMS:] {
		// Is the LMS-substring at index j new, or is it the same as the last one we saw?
		n := sa[j/2]
		if n != lastLen {
			goto New
		}
		if uint64(n) >= uint64(len(text)) {
			// “Length” is really encoded full text, and they match.
			goto Same
		}
		{
			// Compare actual texts.
			n := int(n)
			this := text[j:][:n]
			last := text[lastPos:][:n]
			for i := 0; i < n; i++ {
				if this[i] != last[i] {
					goto New
				}
			}
			goto Same
		}
	New:
		id++
		lastPos = j
		lastLen = n
	Same:
		sa[j/2] = int64(id)
	}
	return id
}

func map_64(sa []int64, numLMS int) {
	w := len(sa)
	for i := len(sa) / 2; i >= 0; i-- {
		j := sa[i]
		if j > 0 {
			w--
			sa[w] = j - 1
		}
	}
}

func recurse_64(sa, oldTmp []int64, numLMS, maxID int) {
	dst, saTmp, text := sa[:numLMS], sa[numLMS:len(sa)-numLMS], sa[len(sa)-numLMS:]

	// 为递归调用设置临时空间。
	// 我们必须传递给 sais_64 一个至少具有 maxID 条目的 tmp 缓冲区。
	//
	// 子问题保证长度最多为 len(sa)/2，
	// 这样 sa 可以同时保存子问题和它的后缀数组。
	// 然而，几乎所有时候，子问题长度 < len(sa)/3，
	// 在这种情况下，sa 有一个子问题大小的中间部分
	// 我们可以重用为临时空间（saTmp）。
	// 当 recurse_64 从 sais_8_64 调用时，oldTmp 长度为 512
	//（来自 text_64），saTmp 通常会大得多，所以我们会使用 saTmp。
	// 当更深的递归回到 recurse_64 时，现在 oldTmp 是
	// 最顶层递归的 saTmp，它通常比当前的 saTmp 大
	//（因为随着递归加深，当前 sa 越来越小），
	// 我们继续重用那个最大的 saTmp，而不是提供的较小的。
	//
	// 为什么子问题长度经常刚好在 len(sa)/3 以下？
	// 参见 Nong、Zhang 和 Chen，第 3.6 节的一个合理的解释。
	// 简言之，len(sa)/2 的情况对应于输入中的 SLSLSLSLSLSL 模式，
	// 即输入字节的完美交替。
	// 真实的文本不会这样。如果每个 L 型索引随机跟随
	// 一个 L 型或 S 型索引，那么一半的子串将是 SLS 形式，
	// 但另一半会更长。在那一半中，
	// 一半（四分之一总体）将是 SLLS；八分之一将是 SLLLS，以此类推。
	// 不计算每个中的最后一个 S（与下一个中的第一个 S 重叠），
	// 这相当于平均长度 2×½ + 3×¼ + 4×⅛ + ... = 3。
	// 所需的空间进一步减少，因为许多
	// 像 SLS 这样的短模式通常是整个文本中重复出现的相同字符序列，
	// 相对于 numLMS 减少了 maxID。
	//
	// 对于短输入，平均值可能对我们不利，但那时我们可以
	// 回退到使用顶层调用中可用的长度-512 tmp。
	// （同样，短的分配也不是什么大问题。）
	//
	// 对于病态输入，我们回退到分配一个新的 tmp，长度为
	// max(maxID, numLMS/2)。这一层递归需要 maxID，
	// 所有更深的递归层将需要不超过 numLMS/2，
	// 因此这 one 次分配保证足以满足整个递归调用栈。
	tmp := oldTmp
	if len(tmp) < len(saTmp) {
		tmp = saTmp
	}
	if len(tmp) < numLMS {
		// TestSAIS/forcealloc 到达此代码。
		n := maxID
		if n < numLMS/2 {
			n = numLMS / 2
		}
		tmp = make([]int64, n)
	}

	// sais_64 要求调用者安排清除 dst，
	// 因为通常调用者可能知道 dst 是
	// 新分配的且已经清除。但这一个不是。
	clear(dst)
	sais_64(text, maxID, dst, tmp)
}

func unmap_8_64(text []byte, sa []int64, numLMS int) {
	unmap := sa[len(sa)-numLMS:]
	j := len(unmap)

	// "LMS 子串迭代器"（参见上面的 placeLMS_8_64）。
	c0, c1, isTypeS := byte(0), byte(0), false
	for i := len(text) - 1; i >= 0; i-- {
		c0, c1 = text[i], c0
		if c0 < c1 {
			isTypeS = true
		} else if c0 > c1 && isTypeS {
			isTypeS = false

			// 填充逆映射。
			j--
			unmap[j] = int64(i + 1)
		}
	}

	// 将逆映射应用到子问题后缀数组。
	sa = sa[:numLMS]
	for i := 0; i < len(sa); i++ {
		sa[i] = unmap[sa[i]]
	}
}

func unmap_32(text []int32, sa []int32, numLMS int) {
	unmap := sa[len(sa)-numLMS:]
	j := len(unmap)

	// "LMS 子串迭代器"（参见上面的 placeLMS_32）。
	c0, c1, isTypeS := int32(0), int32(0), false
	for i := len(text) - 1; i >= 0; i-- {
		c0, c1 = text[i], c0
		if c0 < c1 {
			isTypeS = true
		} else if c0 > c1 && isTypeS {
			isTypeS = false

			// 填充逆映射。
			j--
			unmap[j] = int32(i + 1)
		}
	}

	// 将逆映射应用到子问题后缀数组。
	sa = sa[:numLMS]
	for i := 0; i < len(sa); i++ {
		sa[i] = unmap[sa[i]]
	}
}

func unmap_64(text []int64, sa []int64, numLMS int) {
	unmap := sa[len(sa)-numLMS:]
	j := len(unmap)

	// "LMS 子串迭代器"（参见上面的 placeLMS_64）。
	c0, c1, isTypeS := int64(0), int64(0), false
	for i := len(text) - 1; i >= 0; i-- {
		c0, c1 = text[i], c0
		if c0 < c1 {
			isTypeS = true
		} else if c0 > c1 && isTypeS {
			isTypeS = false

			// 填充逆映射。
			j--
			unmap[j] = int64(i + 1)
		}
	}

	// 将逆映射应用到子问题后缀数组。
	sa = sa[:numLMS]
	for i := 0; i < len(sa); i++ {
		sa[i] = unmap[sa[i]]
	}
}

func expand_8_64(text []byte, freq, bucket, sa []int64, numLMS int) {
	bucketMax_8_64(text, freq, bucket)
	bucket = bucket[:256] // 消除下面 bucket[c] 的边界检查

	// 向后循环遍历 sa，始终跟踪
	// 接下来要从 sa[:numLMS] 填充的索引。
	// 当我们到达一个时，填充它。
	// 其余槽位置清零；它们里面有死值。
	x := numLMS - 1
	saX := sa[x]
	c := text[saX]
	b := bucket[c] - 1
	bucket[c] = b

	for i := len(sa) - 1; i >= 0; i-- {
		if i != int(b) {
			sa[i] = 0
			continue
		}
		sa[i] = saX

		// 加载下一个要放置的条目（如果有）。
		if x > 0 {
			x--
			saX = sa[x] // TODO 边界检查
			c = text[saX]
			b = bucket[c] - 1
			bucket[c] = b
		}
	}
}

func expand_32(text []int32, freq, bucket, sa []int32, numLMS int) {
	bucketMax_32(text, freq, bucket)

	// 向后循环遍历 sa，始终跟踪
	// 接下来要从 sa[:numLMS] 填充的索引。
	// 当我们到达一个时，填充它。
	// 其余槽位置清零；它们里面有死值。
	x := numLMS - 1
	saX := sa[x]
	c := text[saX]
	b := bucket[c] - 1
	bucket[c] = b

	for i := len(sa) - 1; i >= 0; i-- {
		if i != int(b) {
			sa[i] = 0
			continue
		}
		sa[i] = saX

		// 加载下一个要放置的条目（如果有）。
		if x > 0 {
			x--
			saX = sa[x] // TODO 边界检查
			c = text[saX]
			b = bucket[c] - 1
			bucket[c] = b
		}
	}
}

func expand_64(text []int64, freq, bucket, sa []int64, numLMS int) {
	bucketMax_64(text, freq, bucket)

	// 向后循环遍历 sa，始终跟踪
	// 接下来要从 sa[:numLMS] 填充的索引。
	// 当我们到达一个时，填充它。
	// 其余槽位置清零；它们里面有死值。
	x := numLMS - 1
	saX := sa[x]
	c := text[saX]
	b := bucket[c] - 1
	bucket[c] = b

	for i := len(sa) - 1; i >= 0; i-- {
		if i != int(b) {
			sa[i] = 0
			continue
		}
		sa[i] = saX

		// 加载下一个要放置的条目（如果有）。
		if x > 0 {
			x--
			saX = sa[x] // TODO 边界检查
			c = text[saX]
			b = bucket[c] - 1
			bucket[c] = b
		}
	}
}

func induceL_8_64(text []byte, sa, freq, bucket []int64) {
	// 初始化字符桶左侧的位置。
	bucketMin_8_64(text, freq, bucket)
	bucket = bucket[:256] // 消除下面 bucket[cB] 的边界检查

	// 此扫描类似于上面的 induceSubL_8_64。
	// 那个扫描安排清除除最左边 L 型索引外的所有索引。
	// 此扫描保留所有 L 型索引和原始 S 型索引，
	// 但它对正的最左边 L 型索引取反
	//（那些 induceS_8_64 需要处理的）。

	// expand_8_64 遗漏了隐含的条目 sa[-1] == len(text)，
	// 对应于识别的 L 型索引 len(text)-1。
	// 在正式从左到右扫描 sa 之前处理它。
	// 参见循环中的正文注释。
	k := len(text) - 1
	c0, c1 := text[k-1], text[k]
	if c0 < c1 {
		k = -k
	}

	// 缓存最近使用的桶索引。
	cB := c1
	b := bucket[cB]
	sa[b] = int64(k)
	b++

	for i := 0; i < len(sa); i++ {
		j := int(sa[i])
		if j <= 0 {
			// 跳过空或取反的条目（包括取反的零）。
			continue
		}

		// 索引 j 在工作队列中，意味着 k := j-1 是 L 型，
		// 所以我们现在可以将 k 正确地放入 sa。
		// 如果 k-1 是 L 型，将 k 排队以便稍后在此循环中处理。
		// 如果 k-1 是 S 型（text[k-1] < text[k]），将 -k 排队保留给调用者。
		// 如果 k 为零，k-1 不存在，所以我们只需要将它留给调用者。
		// 调用者无法区分空槽和非空零，但没有必要区分它们：
		// 最终的后缀数组最终会在某处有一个真正的零，
		// 那将是一个真实的零。
		k := j - 1
		c1 := text[k]
		if k > 0 {
			if c0 := text[k-1]; c0 < c1 {
				k = -k
			}
		}

		if cB != c1 {
			bucket[cB] = b
			cB = c1
			b = bucket[cB]
		}
		sa[b] = int64(k)
		b++
	}
}

func induceL_32(text []int32, sa, freq, bucket []int32) {
	// 初始化字符桶左侧的位置。
	bucketMin_32(text, freq, bucket)

	// 此扫描类似于上面的 induceSubL_32。
	// 那个扫描安排清除除最左边 L 型索引外的所有索引。
	// 此扫描保留所有 L 型索引和原始 S 型索引，
	// 但它对正的最左边 L 型索引取反
	//（那些 induceS_32 需要处理的）。

	// expand_32 遗漏了隐含的条目 sa[-1] == len(text)，
	// 对应于识别的 L 型索引 len(text)-1。
	// 在正式从左到右扫描 sa 之前处理它。
	// 参见循环中的正文注释。
	k := len(text) - 1
	c0, c1 := text[k-1], text[k]
	if c0 < c1 {
		k = -k
	}

	// 缓存最近使用的桶索引。
	cB := c1
	b := bucket[cB]
	sa[b] = int32(k)
	b++

	for i := 0; i < len(sa); i++ {
		j := int(sa[i])
		if j <= 0 {
			// 跳过空或取反的条目（包括取反的零）。
			continue
		}

		// 索引 j 在工作队列中，意味着 k := j-1 是 L 型，
		// 所以我们现在可以将 k 正确地放入 sa。
		// 如果 k-1 是 L 型，将 k 排队以便稍后在此循环中处理。
		// 如果 k-1 是 S 型（text[k-1] < text[k]），将 -k 排队保留给调用者。
		// 如果 k 为零，k-1 不存在，所以我们只需要将它留给调用者。
		// 调用者无法区分空槽和非空零，但没有必要区分它们：
		// 最终的后缀数组最终会在某处有一个真正的零，
		// 那将是一个真实的零。
		k := j - 1
		c1 := text[k]
		if k > 0 {
			if c0 := text[k-1]; c0 < c1 {
				k = -k
			}
		}

		if cB != c1 {
			bucket[cB] = b
			cB = c1
			b = bucket[cB]
		}
		sa[b] = int32(k)
		b++
	}
}

func induceL_64(text []int64, sa, freq, bucket []int64) {
	// 初始化字符桶左侧的位置。
	bucketMin_64(text, freq, bucket)

	// 此扫描类似于上面的 induceSubL_64。
	// 那个扫描安排清除除最左边 L 型索引外的所有索引。
	// 此扫描保留所有 L 型索引和原始 S 型索引，
	// 但它对正的最左边 L 型索引取反
	//（那些 induceS_64 需要处理的）。

	// expand_64 遗漏了隐含的条目 sa[-1] == len(text)，
	// 对应于识别的 L 型索引 len(text)-1。
	// 在正式从左到右扫描 sa 之前处理它。
	// 参见循环中的正文注释。
	k := len(text) - 1
	c0, c1 := text[k-1], text[k]
	if c0 < c1 {
		k = -k
	}

	// 缓存最近使用的桶索引。
	cB := c1
	b := bucket[cB]
	sa[b] = int64(k)
	b++

	for i := 0; i < len(sa); i++ {
		j := int(sa[i])
		if j <= 0 {
			// 跳过空或取反的条目（包括取反的零）。
			continue
		}

		// 索引 j 在工作队列中，意味着 k := j-1 是 L 型，
		// 所以我们现在可以将 k 正确地放入 sa。
		// 如果 k-1 是 L 型，将 k 排队以便稍后在此循环中处理。
		// 如果 k-1 是 S 型（text[k-1] < text[k]），将 -k 排队保留给调用者。
		// 如果 k 为零，k-1 不存在，所以我们只需要将它留给调用者。
		// 调用者无法区分空槽和非空零，但没有必要区分它们：
		// 最终的后缀数组最终会在某处有一个真正的零，
		// 那将是一个真实的零。
		k := j - 1
		c1 := text[k]
		if k > 0 {
			if c0 := text[k-1]; c0 < c1 {
				k = -k
			}
		}

		if cB != c1 {
			bucket[cB] = b
			cB = c1
			b = bucket[cB]
		}
		sa[b] = int64(k)
		b++
	}
}

func induceS_8_64(text []byte, sa, freq, bucket []int64) {
	// 初始化字符桶右侧的位置。
	bucketMax_8_64(text, freq, bucket)
	bucket = bucket[:256] // 消除下面 bucket[cB] 的边界检查

	cB := byte(0)
	b := bucket[cB]

	for i := len(sa) - 1; i >= 0; i-- {
		j := int(sa[i])
		if j >= 0 {
			// 跳过未标记的条目。
			//（此循环看不到空条目；0 表示真实的零索引。）
			continue
		}

		// 负 j 是工作队列条目；重写为正 j 用于最终后缀数组。
		j = -j
		sa[i] = int64(j)

		// 索引 j 在工作队列中（编码为 -j，但现在已解码），
		// 意味着 k := j-1 是 L 型，
		// 所以我们现在可以将 k 正确地放入 sa。
		// 如果 k-1 是 S 型，将 -k 排队以便稍后在此循环中处理。
		// 如果 k-1 是 L 型（text[k-1] > text[k]），将 k 排队保留给调用者。
		// 如果 k 为零，k-1 不存在，所以我们只需要将它留给调用者。
		k := j - 1
		c1 := text[k]
		if k > 0 {
			if c0 := text[k-1]; c0 <= c1 {
				k = -k
			}
		}

		if cB != c1 {
			bucket[cB] = b
			cB = c1
			b = bucket[cB]
		}
		b--
		sa[b] = int64(k)
	}
}

func induceS_32(text []int32, sa, freq, bucket []int32) {
	// 初始化字符桶右侧的位置。
	bucketMax_32(text, freq, bucket)

	cB := int32(0)
	b := bucket[cB]

	for i := len(sa) - 1; i >= 0; i-- {
		j := int(sa[i])
		if j >= 0 {
			// 跳过未标记的条目。
			//（此循环看不到空条目；0 表示真实的零索引。）
			continue
		}

		// 负 j 是工作队列条目；重写为正 j 用于最终后缀数组。
		j = -j
		sa[i] = int32(j)

		// 索引 j 在工作队列中（编码为 -j，但现在已解码），
		// 意味着 k := j-1 是 L 型，
		// 所以我们现在可以将 k 正确地放入 sa。
		// 如果 k-1 是 S 型，将 -k 排队以便稍后在此循环中处理。
		// 如果 k-1 是 L 型（text[k-1] > text[k]），将 k 排队保留给调用者。
		// 如果 k 为零，k-1 不存在，所以我们只需要将它留给调用者。
		k := j - 1
		c1 := text[k]
		if k > 0 {
			if c0 := text[k-1]; c0 <= c1 {
				k = -k
			}
		}

		if cB != c1 {
			bucket[cB] = b
			cB = c1
			b = bucket[cB]
		}
		b--
		sa[b] = int32(k)
	}
}

func induceS_64(text []int64, sa, freq, bucket []int64) {
	// 初始化字符桶右侧的位置。
	bucketMax_64(text, freq, bucket)

	cB := int64(0)
	b := bucket[cB]

	for i := len(sa) - 1; i >= 0; i-- {
		j := int(sa[i])
		if j >= 0 {
			// 跳过未标记的条目。
			//（此循环看不到空条目；0 表示真实的零索引。）
			continue
		}

		// 负 j 是工作队列条目；重写为正 j 用于最终后缀数组。
		j = -j
		sa[i] = int64(j)

		// 索引 j 在工作队列中（编码为 -j，但现在已解码），
		// 意味着 k := j-1 是 L 型，
		// 所以我们现在可以将 k 正确地放入 sa。
		// 如果 k-1 是 S 型，将 -k 排队以便稍后在此循环中处理。
		// 如果 k-1 是 L 型（text[k-1] > text[k]），将 k 排队保留给调用者。
		// 如果 k 为零，k-1 不存在，所以我们只需要将它留给调用者。
		k := j - 1
		c1 := text[k]
		if k > 0 {
			if c0 := text[k-1]; c0 <= c1 {
				k = -k
			}
		}

		if cB != c1 {
			bucket[cB] = b
			cB = c1
			b = bucket[cB]
		}
		b--
		sa[b] = int64(k)
	}
}
