// Code generated by gen_sort_variants.go; DO NOT EDIT.

// Copyright 2022 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sort

// insertionSort_func 使用插入排序对 data[a:b] 进行排序。
func insertionSort_func(data lessSwap, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && data.Less(j, j-1); j-- {
			data.Swap(j, j-1)
		}
	}
}

// siftDown_func 在 data[lo:hi] 上实现堆属性。
// first 是堆根在数组中的偏移量。
func siftDown_func(data lessSwap, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && data.Less(first+child, first+child+1) {
			child++
		}
		if !data.Less(first+root, first+child) {
			return
		}
		data.Swap(first+root, first+child)
		root = child
	}
}

func heapSort_func(data lessSwap, a, b int) {
	first := a
	lo := 0
	hi := b - a

	// 构建堆，最大元素在顶部。
	for i := (hi - 1) / 2; i >= 0; i-- {
		siftDown_func(data, i, hi, first)
	}

	// 弹出元素，最大元素优先，到 data 的末尾。
	for i := hi - 1; i >= 0; i-- {
		data.Swap(first, first+i)
		siftDown_func(data, lo, i, first)
	}
}

// pdqsort_func 对 data[a:b] 进行排序。
// 该算法基于 pattern-defeating quicksort (pdqsort)，但没有 BlockQuicksort 的优化。
// pdqsort 论文：https://arxiv.org/pdf/2106.05123.pdf
// C++ 实现：https://github.com/orlp/pdqsort
// Rust 实现：https://docs.rs/pdqsort/latest/pdqsort/
// limit 是在回退到堆排序之前允许的坏（非常不平衡）枢轴的数量。
func pdqsort_func(data lessSwap, a, b, limit int) {
	const maxInsertion = 12

	var (
		wasBalanced    = true // 上一次分区是否相当平衡
		wasPartitioned = true // 切片是否已经分区
	)

	for {
		length := b - a

		if length <= maxInsertion {
			insertionSort_func(data, a, b)
			return
		}

		// 如果做了太多坏的选择，回退到堆排序。
		if limit == 0 {
			heapSort_func(data, a, b)
			return
		}

		// 如果上一次分区不平衡，我们需要打破模式。
		if !wasBalanced {
			breakPatterns_func(data, a, b)
			limit--
		}

		pivot, hint := choosePivot_func(data, a, b)
		if hint == decreasingHint {
			reverseRange_func(data, a, b)
			// 所选枢轴是数组开头后 pivot-a 个元素。
			// 反转后，它是数组末尾前 pivot-a 个元素。
			// 这个想法来自 Rust 的实现。
			pivot = (b - 1) - (pivot - a)
			hint = increasingHint
		}

		// 切片可能已经排序。
		if wasBalanced && wasPartitioned && hint == increasingHint {
			if partialInsertionSort_func(data, a, b) {
				return
			}
		}

		// 切片可能包含许多重复元素，将切片分区为等于枢轴的元素和大于枢轴的元素。
		if a > 0 && !data.Less(a-1, pivot) {
			mid := partitionEqual_func(data, a, b, pivot)
			a = mid
			continue
		}

		mid, alreadyPartitioned := partition_func(data, a, b, pivot)
		wasPartitioned = alreadyPartitioned

		leftLen, rightLen := mid-a, b-mid
		balanceThreshold := length / 8
		if leftLen < rightLen {
			wasBalanced = leftLen >= balanceThreshold
			pdqsort_func(data, a, mid, limit)
			a = mid + 1
		} else {
			wasBalanced = rightLen >= balanceThreshold
			pdqsort_func(data, mid+1, b, limit)
			b = mid
		}
	}
}

// partition_func 执行一次快速排序分区。
// 设 p = data[pivot]
// 移动 data[a:b] 中的元素，使得对于 i<newpivot 有 data[i]<p，对于 j>newpivot 有 data[j]>=p。
// 返回时，data[newpivot] = p
func partition_func(data lessSwap, a, b, pivot int) (newpivot int, alreadyPartitioned bool) {
	data.Swap(a, pivot)
	i, j := a+1, b-1 // i 和 j 包括待分区的元素

	for i <= j && data.Less(i, a) {
		i++
	}
	for i <= j && !data.Less(j, a) {
		j--
	}
	if i > j {
		data.Swap(j, a)
		return j, true
	}
	data.Swap(i, j)
	i++
	j--

	for {
		for i <= j && data.Less(i, a) {
			i++
		}
		for i <= j && !data.Less(j, a) {
			j--
		}
		if i > j {
			break
		}
		data.Swap(i, j)
		i++
		j--
	}
	data.Swap(j, a)
	return j, false
}

// partitionEqual_func 将 data[a:b] 分区为等于 data[pivot] 的元素，后跟大于 data[pivot] 的元素。
// 它假设 data[a:b] 不包含小于 data[pivot] 的元素。
func partitionEqual_func(data lessSwap, a, b, pivot int) (newpivot int) {
	data.Swap(a, pivot)
	i, j := a+1, b-1 // i 和 j 包括待分区的元素

	for {
		for i <= j && !data.Less(a, i) {
			i++
		}
		for i <= j && data.Less(a, j) {
			j--
		}
		if i > j {
			break
		}
		data.Swap(i, j)
		i++
		j--
	}
	return i
}

// partialInsertionSort_func 对切片进行部分排序，如果在结束时切片已排序则返回 true。
func partialInsertionSort_func(data lessSwap, a, b int) bool {
	const (
		maxSteps         = 5  // 将被移动的相邻乱序对的最大数量
		shortestShifting = 50 // 短数组不移动任何元素
	)
	i := a + 1
	for j := 0; j < maxSteps; j++ {
		for i < b && !data.Less(i, i-1) {
			i++
		}

		if i == b {
			return true
		}

		if b-a < shortestShifting {
			return false
		}

		data.Swap(i, i-1)

		// 将较小的移到左边。
		if i-a >= 2 {
			for j := i - 1; j >= 1; j-- {
				if !data.Less(j, j-1) {
					break
				}
				data.Swap(j, j-1)
			}
		}
		// 将较大的移到右边。
		if b-i >= 2 {
			for j := i + 1; j < b; j++ {
				if !data.Less(j, j-1) {
					break
				}
				data.Swap(j, j-1)
			}
		}
	}
	return false
}

// breakPatterns_func 分散一些元素，试图打破可能导致快速排序分区不平衡的某些模式。
func breakPatterns_func(data lessSwap, a, b int) {
	length := b - a
	if length >= 8 {
		random := xorshift(length)
		modulus := nextPowerOfTwo(length)

		for idx := a + (length/4)*2 - 1; idx <= a+(length/4)*2+1; idx++ {
			other := int(uint(random.Next()) & (modulus - 1))
			if other >= length {
				other -= length
			}
			data.Swap(idx, a+other)
		}
	}
}

// choosePivot_func 在 data[a:b] 中选择枢轴。
//
// [0,8)：选择静态枢轴。
// [8,shortestNinther)：使用简单三数取中法。
// [shortestNinther,∞)：使用 Tukey ninther 方法。
func choosePivot_func(data lessSwap, a, b int) (pivot int, hint sortedHint) {
	const (
		shortestNinther = 50
		maxSwaps        = 4 * 3
	)

	l := b - a

	var (
		swaps int
		i     = a + l/4*1
		j     = a + l/4*2
		k     = a + l/4*3
	)

	if l >= 8 {
		if l >= shortestNinther {
			// Tukey ninther 方法，这个想法来自 Rust 的实现。
			i = medianAdjacent_func(data, i, &swaps)
			j = medianAdjacent_func(data, j, &swaps)
			k = medianAdjacent_func(data, k, &swaps)
		}
		// 找到 i, j, k 中的中位数并存储到 j。
		j = median_func(data, i, j, k, &swaps)
	}

	switch swaps {
	case 0:
		return j, increasingHint
	case maxSwaps:
		return j, decreasingHint
	default:
		return j, unknownHint
	}
}

// order2_func 返回 x,y，其中 data[x] <= data[y]，x,y = a,b 或 x,y = b,a。
func order2_func(data lessSwap, a, b int, swaps *int) (int, int) {
	if data.Less(b, a) {
		*swaps++
		return b, a
	}
	return a, b
}

// median_func 返回 x，其中 data[x] 是 data[a],data[b],data[c] 的中位数，x 为 a、b 或 c 之一。
func median_func(data lessSwap, a, b, c int, swaps *int) int {
	a, b = order2_func(data, a, b, swaps)
	b, c = order2_func(data, b, c, swaps)
	a, b = order2_func(data, a, b, swaps)
	return b
}

// medianAdjacent_func 找到 data[a - 1], data[a], data[a + 1] 的中位数并将索引存储到 a。
func medianAdjacent_func(data lessSwap, a int, swaps *int) int {
	return median_func(data, a-1, a, a+1, swaps)
}

func reverseRange_func(data lessSwap, a, b int) {
	i := a
	j := b - 1
	for i < j {
		data.Swap(i, j)
		i++
		j--
	}
}

func swapRange_func(data lessSwap, a, b, n int) {
	for i := 0; i < n; i++ {
		data.Swap(a+i, b+i)
	}
}

func stable_func(data lessSwap, n int) {
	blockSize := 20 // 必须 > 0
	a, b := 0, blockSize
	for b <= n {
		insertionSort_func(data, a, b)
		a = b
		b += blockSize
	}
	insertionSort_func(data, a, n)

	for blockSize < n {
		a, b = 0, 2*blockSize
		for b <= n {
			symMerge_func(data, a, a+blockSize, b)
			a = b
			b += 2 * blockSize
		}
		if m := a + blockSize; m < n {
			symMerge_func(data, a, m, n)
		}
		blockSize *= 2
	}
}

// symMerge_func 使用 Pok-Son Kim 和 Arne Kutzner 的 SymMerge 算法合并两个已排序的子序列 data[a:m] 和 data[m:b]，
// 论文 "Stable Minimum Storage Merging by Symmetric Comparisons"，
// Susanne Albers 和 Tomasz Radzik 编，Algorithms - ESA 2004，
// Lecture Notes in Computer Science 第 3221 卷，714-723 页。Springer，2004。
//
// 设 M = m-a，N = b-n。不失一般性 M < N。
// 递归深度以 ceil(log(N+M)) 为界。
// 该算法需要 O(M*log(N/M + 1)) 次 data.Less 调用。
// 该算法需要 O((M+N)*log(M)) 次 data.Swap 调用。
//
// 论文给出 O((M+N)*log(M)) 作为赋值次数，假设使用 O(M+N+gcd(M+N)) 次赋值的旋转算法。
// 论文中的论证同样适用于 Swap 操作，特别是块交换旋转仅使用 O(M+N) 次 Swaps。
//
// symMerge 假设参数非退化：a < m && m < b。
// 让调用者检查此条件可以消除许多叶递归调用，这提高了性能。
func symMerge_func(data lessSwap, a, m, b int) {
	// 如果 data[a:m] 只包含一个元素，通过直接将 data[a] 插入 data[m:b]
	// 来避免 symMerge 的不必要的递归。
	if m-a == 1 {
		// 使用二分搜索找到最小的索引 i，
		// 使得对于 m <= i < b 有 data[i] >= data[a]。
		// 如果不存在这样的索引，以 i == b 退出搜索循环。
		i := m
		j := b
		for i < j {
			h := int(uint(i+j) >> 1)
			if data.Less(h, a) {
				i = h + 1
			} else {
				j = h
			}
		}
		// 交换值直到 data[a] 到达 i 之前的位置。
		for k := a; k < i-1; k++ {
			data.Swap(k, k+1)
		}
		return
	}

	// 如果 data[m:b] 只包含一个元素，通过直接将 data[m] 插入 data[a:m]
	// 来避免 symMerge 的不必要的递归。
	if b-m == 1 {
		// 使用二分搜索找到最小的索引 i，
		// 使得对于 a <= i < m 有 data[i] > data[m]。
		// 如果不存在这样的索引，以 i == m 退出搜索循环。
		i := a
		j := m
		for i < j {
			h := int(uint(i+j) >> 1)
			if !data.Less(m, h) {
				i = h + 1
			} else {
				j = h
			}
		}
		// 交换值直到 data[m] 到达位置 i。
		for k := m; k > i; k-- {
			data.Swap(k, k-1)
		}
		return
	}

	mid := int(uint(a+b) >> 1)
	n := mid + m
	var start, r int
	if m > mid {
		start = n - b
		r = mid
	} else {
		start = a
		r = m
	}
	p := n - 1

	for start < r {
		c := int(uint(start+r) >> 1)
		if !data.Less(p-c, c) {
			start = c + 1
		} else {
			r = c
		}
	}

	end := n - start
	if start < m && m < end {
		rotate_func(data, start, m, end)
	}
	if a < start && start < mid {
		symMerge_func(data, a, start, mid)
	}
	if mid < end && end < b {
		symMerge_func(data, mid, end, b)
	}
}

// rotate_func 旋转 data 中两个连续的块 u = data[a:m] 和 v = data[m:b]：
// 形式为 'x u v y' 的数据被更改为 'x v u y'。
// rotate 执行最多 b-a 次 data.Swap 调用，
// 它假设参数非退化：a < m && m < b。
func rotate_func(data lessSwap, a, m, b int) {
	i := m - a
	j := b - m

	for i != j {
		if i > j {
			swapRange_func(data, m-i, m, j)
			i -= j
		} else {
			swapRange_func(data, m-i, m+j-i, i)
			j -= i
		}
	}
	// i == j
	swapRange_func(data, m-i, m, i)
}
